name: resign-a9

on:
  workflow_dispatch:
    inputs:
      ZIP_URL:
        description: 'URL of the input zip'
        required: true
        default: ''

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:runner-20.04
    steps:

    - name: Checkout A9 scripts
      uses: actions/checkout@v4
      with:
        repository: TomKing062/action_big_resign_with_magisk
        ref: a9_boot_with_recovery_cpio
        path: main

    - name: patch
      run: |
        sudo apt update
        sudo apt -y install build-essential python openssl curl wget busybox
        wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && sudo python2.7 get-pip.py
        pip2 install pycryptodome
        curl -o original.zip -L "${{ github.event.inputs.ZIP_URL }}"
        curl -o avbtool.tgz -L "https://android.googlesource.com/platform/external/avb/+archive/refs/heads/pie-release.tar.gz"
        curl -o magisk.apk -L $(curl -s https://api.github.com/repos/topjohnwu/Magisk/releases | grep -Po -m 1 '(?<=download_url\"\: \").*Magisk.*Magisk.*apk')
        wget https://raw.githubusercontent.com/magojohnji/magiskboot-linux/main/x86_64/magiskboot
        chmod +x magiskboot
        chmod +x main/*.sh
        mv main/sign.sh ./
        ./sign.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: resigned
        path: resigned.zip
        if-no-files-found: error

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          resigned.zip
        name: ${{ github.run_id }}
        tag_name: "resigned-${{ github.run_id }}"
        body: |
          URL: ${{ github.event.inputs.ZIP_URL }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
